title: Steve's Thoughts
author: Steve Aylor
email: SteveAylor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome description for my new site here. 
# social links
twitter_username: @saylor
github_username:  saylor

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
